[package]
name = "rust_practise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "*"
thiserror = "1.0.40"
serde_json = "1.0.96"
serde = { version = "1.0.163", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
time = { version = "0.3.21" }
chrono = "0.4"
moka = { version = "0.12.1", features = ["future"] }
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
base64 = "*"
hex = "*"
enum_dispatch = "*"
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.15"
