[package]
name = "rust_practise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum-server = { version = "*", features = ["tls-rustls"] }
axum = "*"
error-stack = "0.3.1"
thiserror = "1.0.40"
serde_json = "1.0.96"
serde = { version = "1.0.163", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
time = { version = "0.3.21" }
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
async-trait = "*"
reqwest = { version = "*", features = ["rustls-tls-native-roots", "blocking"] }
futures = "*"
