name: CI-pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting
        shell: bash
        run: cargo +nightly fmt --all --check

  typos:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Store PR title
        shell: bash
        run: echo '${{ github.event.pull_request.title }}' > pr_title.txt

      - name: Spell check
        uses: crate-ci/typos@master

